spring.application.name=ProductWebViewerSpring

spring.datasource.url=jdbc:sqlite:practice.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always

app.auth.admin-password=admin123
